/*!
PrivMX Bridge.
Copyright © 2024 Simplito sp. z o.o.

This file is part of the PrivMX Platform (https://privmx.dev).
This software is Licensed under the PrivMX Free License.

See the License for the specific language governing permissions and
limitations under the License.
*/

import "q2-test";
import * as assert from "assert";
import * as fs from "fs";
import * as path from "path";
import * as types from "../../../../types";
import { LadderMath } from "../../../../service/cloud/keytree/LadderMath";
import { TreeValidator } from "../../../../service/cloud/keytree/TreeValidator";

/**
 * Runs the bridge's production validator over tree states produced by the **C++ endpoint**.
 *
 * The two implementations have to agree exactly. The client computes a complete tree state with real EC keys and
 * real ECIES and submits it; the server accepts or rejects it on structure alone. Unit tests on either side can
 * only check each half against its own reading of the rules — a divergence between the two would slip through
 * both and surface as a client that simply cannot remove anyone.
 *
 * The fixture is generated by `privmx-endpoint/test/tools/keytree_state_dump.cpp` (see its header and
 * privmx-endpoint/test/tools/README.md for how to regenerate it). Wrapped blobs are truncated there, since a
 * structural validator checks that an edge carries a ciphertext and never what is inside one.
 *
 * If this file fails, one of the two implementations changed its idea of what a well-formed state is. That is
 * exactly what it is here to catch.
 */

interface WireTree {
    numLeaves: number;
    leafAssignment: string[];
    nodes: {nodeIndex: number, generation: number, publicKey: string}[];
    edges: {
        isGrantEdge?: boolean,
        parentIndex?: number,
        parentGeneration: number,
        childKind: string,
        childIndex?: number,
        childGeneration?: number,
        childUserId?: string,
        data: string,
    }[];
}

interface CreateCase {
    kind: "create";
    epoch: number;
    members: string[];
    tree: WireTree;
}

interface RemoveCase {
    kind: "remove";
    beforeEpoch: number;
    afterEpoch: number;
    removed: string;
    position: number;
    members: string[];
    remaining: string[];
    rungs: {at: number, target: number}[];
    before: WireTree;
    after: WireTree;
}

interface AddCase {
    kind: "add";
    epoch: number;
    added: string;
    position: number;
    members: string[];
    after_members: string[];
    before: WireTree;
    after: WireTree;
}

type Fixture = {cases: (CreateCase|RemoveCase|AddCase)[]};

function loadFixture(): Fixture {
    // Read from `src`, not `out`: the build copies TypeScript only, and a JSON test vector belongs with the test
    // that owns it rather than in the compiler's output.
    const fixturePath = path.resolve(__dirname, "../../../../..", "src/test/fixtures/keytree-states.json");
    return JSON.parse(fs.readFileSync(fixturePath, "utf8")) as Fixture;
}

function asTree(tree: WireTree): types.cloud.GroupTreeState {
    return tree as unknown as types.cloud.GroupTreeState;
}

function roster(members: string[]) {
    return {users: members as types.cloud.UserId[], managers: [] as types.cloud.UserId[]};
}

const fixture = loadFixture();

describe("tree states produced by the endpoint", () => {
    it("the fixture covers creation, removal and addition", () => {
        const kinds = new Set(fixture.cases.map(c => c.kind));
        assert.ok(kinds.has("create"), "no creation cases");
        assert.ok(kinds.has("remove"), "no removal cases");
        assert.ok(kinds.has("add"), "no addition cases");
        assert.ok(fixture.cases.length >= 20, `only ${fixture.cases.length} cases`);
    });
    
    const creates = fixture.cases.filter((c): c is CreateCase => c.kind === "create");
    each<[CreateCase]>(creates.map(c => [c])).it("a freshly built tree of %#", ([testCase]) => {
        const problems = TreeValidator.validateState(asTree(testCase.tree), roster(testCase.members), testCase.epoch);
        assert.deepStrictEqual(
            problems, [],
            `N=${testCase.tree.numLeaves}: ${JSON.stringify(problems)}`,
        );
    });
    
    const removals = fixture.cases.filter((c): c is RemoveCase => c.kind === "remove");
    each<[RemoveCase]>(removals.map(c => [c])).it("a removal of %#", ([testCase]) => {
        const transition = TreeValidator.validateRemoval(
            asTree(testCase.before), asTree(testCase.after),
            testCase.removed as types.cloud.UserId, testCase.beforeEpoch, testCase.afterEpoch,
        );
        assert.deepStrictEqual(
            transition, [],
            `N=${testCase.before.numLeaves} removing ${testCase.removed}: ${JSON.stringify(transition)}`,
        );
        const state = TreeValidator.validateState(
            asTree(testCase.after), roster(testCase.remaining), testCase.afterEpoch,
        );
        assert.deepStrictEqual(
            state, [],
            `N=${testCase.before.numLeaves} after removing ${testCase.removed}: ${JSON.stringify(state)}`,
        );
    });
    
    each<[RemoveCase]>(removals.map(c => [c])).it("the rungs published with removal %#", ([testCase]) => {
        // The unit rung is mandatory: without it the epoch the removal creates cannot reach the one before it,
        // and the group's own history is orphaned at the moment of the removal.
        const result = LadderMath.validateRungSet(testCase.rungs, testCase.afterEpoch, 1);
        assert.ok(result.ok, JSON.stringify(result));
        assert.ok(
            testCase.rungs.some(r => r.at === testCase.afterEpoch && r.target === testCase.beforeEpoch),
            `no unit rung ${testCase.afterEpoch}->${testCase.beforeEpoch} in ${JSON.stringify(testCase.rungs)}`,
        );
    });
    
    const additions = fixture.cases.filter((c): c is AddCase => c.kind === "add");
    each<[AddCase]>(additions.map(c => [c])).it("an addition of %#", ([testCase]) => {
        const transition = TreeValidator.validateAddition(
            asTree(testCase.before), asTree(testCase.after), testCase.added as types.cloud.UserId,
            testCase.position, testCase.epoch, testCase.epoch,
        );
        assert.deepStrictEqual(
            transition, [],
            `N=${testCase.before.numLeaves} adding at ${testCase.position}: ${JSON.stringify(transition)}`,
        );
        const state = TreeValidator.validateState(
            asTree(testCase.after), roster(testCase.after_members), testCase.epoch,
        );
        assert.deepStrictEqual(
            state, [],
            `N=${testCase.before.numLeaves} after adding at ${testCase.position}: ${JSON.stringify(state)}`,
        );
    });
    
    it("SECURITY: an addition never advances the epoch", () => {
        // Checked over the real fixture rather than a hand-written case: if the client ever started rotating the
        // grant key on an addition, every container the group can read would go stale on each new member.
        for (const testCase of additions) {
            const grant = testCase.after.edges.find(e => e.isGrantEdge);
            assert.ok(grant, "no grant edge after addition");
            assert.strictEqual(grant.parentGeneration, testCase.epoch, "addition moved the epoch");
        }
    });
    
    it("SECURITY: a removal refreshes every node on the departing leaf's path and no other", () => {
        for (const testCase of removals) {
            const before = new Map(testCase.before.nodes.map(n => [n.nodeIndex, n]));
            let refreshed = 0;
            for (const node of testCase.after.nodes) {
                const previous = before.get(node.nodeIndex);
                if (!previous) {
                    continue;
                }
                if (node.generation !== previous.generation) {
                    refreshed++;
                    assert.notStrictEqual(
                        node.publicKey, previous.publicKey,
                        `node ${node.nodeIndex} bumped its generation but kept its key`,
                    );
                }
            }
            // Which nodes those are is checked by validateRemoval above; here we only insist that a removal in a
            // tree with internal nodes actually refreshed something.
            if (testCase.before.nodes.length > 0) {
                assert.ok(refreshed > 0, `removal in N=${testCase.before.numLeaves} refreshed nothing`);
            }
        }
    });
});
