/*!
PrivMX Bridge.
Copyright © 2024 Simplito sp. z o.o.

This file is part of the PrivMX Platform (https://privmx.dev).
This software is Licensed under the PrivMX Free License.

See the License for the specific language governing permissions and
limitations under the License.
*/

import "q2-test";
import * as assert from "assert";
import * as fs from "fs";
import * as path from "path";
import * as types from "../../../../types";
import { LadderMath } from "../../../../service/cloud/keytree/LadderMath";
import { TreeValidator } from "../../../../service/cloud/keytree/TreeValidator";

/**
 * Runs the bridge's production validator over tree states produced by the **C++ endpoint**.
 *
 * The two implementations have to agree exactly. The client computes a complete tree state with real EC keys and
 * real ECIES and submits it; the server accepts or rejects it on structure alone. Unit tests on either side can
 * only check each half against its own reading of the rules — a divergence between the two would slip through
 * both and surface as a client that simply cannot remove anyone.
 *
 * The fixture is generated by `privmx-endpoint/test/tools/keytree_state_dump.cpp` (see its header and
 * privmx-endpoint/test/tools/README.md for how to regenerate it). Wrapped blobs appear as `b64:<length>:<digest>`
 * rather than in full, since a structural validator checks that an edge carries a ciphertext and never what is
 * inside one — but as a digest rather than a prefix, because the first 46 characters of an ECIES blob are a fixed
 * header and a prefix therefore looked identical on every edge.
 *
 * If this file fails, one of the two implementations changed its idea of what a well-formed state is. That is
 * exactly what it is here to catch.
 */

interface WireTree {
    numLeaves: number;
    leafAssignment: string[];
    nodes: {nodeIndex: number, generation: number, publicKey: string}[];
    edges: {
        isGrantEdge?: boolean,
        parentIndex?: number,
        parentGeneration: number,
        childKind: string,
        childIndex?: number,
        childGeneration?: number,
        childUserId?: string,
        data: string,
    }[];
}

interface CreateCase {
    kind: "create";
    epoch: number;
    members: string[];
    tree: WireTree;
}

interface RemoveCase {
    kind: "remove";
    beforeEpoch: number;
    afterEpoch: number;
    removed: string;
    position: number;
    members: string[];
    remaining: string[];
    rungs: {at: number, target: number}[];
    before: WireTree;
    after: WireTree;
}

interface AddCase {
    kind: "add";
    epoch: number;
    added: string;
    position: number;
    members: string[];
    after_members: string[];
    before: WireTree;
    after: WireTree;
}

type Fixture = {cases: (CreateCase|RemoveCase|AddCase)[]};

function loadFixture(): Fixture {
    // Read from `src`, not `out`: the build copies TypeScript only, and a JSON test vector belongs with the test
    // that owns it rather than in the compiler's output.
    const fixturePath = path.resolve(__dirname, "../../../../..", "src/test/fixtures/keytree-states.json");
    return JSON.parse(fs.readFileSync(fixturePath, "utf8")) as Fixture;
}

function asTree(tree: WireTree): types.cloud.GroupTreeState {
    return tree as unknown as types.cloud.GroupTreeState;
}

function roster(members: string[]) {
    return {users: members as types.cloud.UserId[], managers: [] as types.cloud.UserId[]};
}

/** Every tree a case carries, labelled — a transition has two, a creation one. */
function collectTrees(testCase: CreateCase|RemoveCase|AddCase): Record<string, WireTree> {
    return testCase.kind === "create"
        ? {tree: testCase.tree}
        : {before: testCase.before, after: testCase.after};
}

const fixture = loadFixture();

describe("tree states produced by the endpoint", () => {
    it("the fixture covers creation, removal and addition", () => {
        const kinds = new Set(fixture.cases.map(c => c.kind));
        assert.ok(kinds.has("create"), "no creation cases");
        assert.ok(kinds.has("remove"), "no removal cases");
        assert.ok(kinds.has("add"), "no addition cases");
        assert.ok(fixture.cases.length >= 20, `only ${fixture.cases.length} cases`);
    });
    
    const creates = fixture.cases.filter((c): c is CreateCase => c.kind === "create");
    each<[CreateCase]>(creates.map(c => [c])).it("a freshly built tree of %#", ([testCase]) => {
        const problems = TreeValidator.validateState(asTree(testCase.tree), roster(testCase.members), testCase.epoch);
        assert.deepStrictEqual(
            problems, [],
            `N=${testCase.tree.numLeaves}: ${JSON.stringify(problems)}`,
        );
    });
    
    const removals = fixture.cases.filter((c): c is RemoveCase => c.kind === "remove");
    each<[RemoveCase]>(removals.map(c => [c])).it("a removal of %#", ([testCase]) => {
        const state = TreeValidator.validateState(
            asTree(testCase.after), roster(testCase.remaining), testCase.afterEpoch,
        );
        assert.deepStrictEqual(
            state, [],
            `N=${testCase.before.numLeaves} after removing ${testCase.removed}: ${JSON.stringify(state)}`,
        );
    });
    
    each<[RemoveCase]>(removals.map(c => [c])).it("the rungs published with removal %#", ([testCase]) => {
        // The unit rung is mandatory: without it the epoch the removal creates cannot reach the one before it,
        // and the group's own history is orphaned at the moment of the removal.
        const result = LadderMath.validateRungSet(testCase.rungs, testCase.afterEpoch, 1);
        assert.ok(result.ok, JSON.stringify(result));
        assert.ok(
            testCase.rungs.some(r => r.at === testCase.afterEpoch && r.target === testCase.beforeEpoch),
            `no unit rung ${testCase.afterEpoch}->${testCase.beforeEpoch} in ${JSON.stringify(testCase.rungs)}`,
        );
    });
    
    const additions = fixture.cases.filter((c): c is AddCase => c.kind === "add");
    each<[AddCase]>(additions.map(c => [c])).it("an addition of %#", ([testCase]) => {
        const state = TreeValidator.validateState(
            asTree(testCase.after), roster(testCase.after_members), testCase.epoch,
        );
        assert.deepStrictEqual(
            state, [],
            `N=${testCase.before.numLeaves} after adding at ${testCase.position}: ${JSON.stringify(state)}`,
        );
    });
    
    it("SECURITY: no state reuses one ciphertext across edges", () => {
        // Each edge wraps a different key to a different recipient, so no two may carry the same ciphertext. A
        // state that repeated one wrap would pass every structural rule above while granting the wrong people
        // the wrong keys — the shape would be right and the cryptography wrong.
        //
        // This is checkable only because the fixture carries a digest per blob. It could not be checked while
        // blobs were truncated to a prefix: the first 46 characters of an ECIES ciphertext are a version byte
        // plus the signer's public key, identical for every edge one client writes.
        for (const testCase of fixture.cases) {
            for (const [label, tree] of Object.entries(collectTrees(testCase))) {
                const blobs = tree.edges.map(e => e.data);
                const distinct = new Set(blobs);
                assert.strictEqual(
                    distinct.size, blobs.length,
                    `${testCase.kind} ${label}: ${blobs.length} edges but ${distinct.size} distinct ciphertexts`,
                );
                for (const blob of blobs) {
                    assert.ok(/^b64:\d+:[0-9a-f]{16}$/.test(blob), `edge carries no ciphertext digest: ${blob}`);
                }
            }
        }
    });
    
    it("SECURITY: an addition never advances the epoch", () => {
        // Checked over the real fixture rather than a hand-written case: if the client ever started rotating the
        // grant key on an addition, every container the group can read would go stale on each new member.
        for (const testCase of additions) {
            const grant = testCase.after.edges.find(e => e.isGrantEdge);
            assert.ok(grant, "no grant edge after addition");
            assert.strictEqual(grant.parentGeneration, testCase.epoch, "addition moved the epoch");
        }
    });
    
    it("an addition re-keys the new leaf's path and files it under a new generation", () => {
        // The client cannot wrap to a node it has no key for, so seating anybody below an existing node means
        // re-keying the path to it. What must not happen is the re-keyed node arriving *alongside* the one it
        // replaces: the state would then hold two entries for one index, one of them a key nobody holds.
        for (const testCase of additions) {
            const indices = testCase.after.nodes.map(n => n.nodeIndex);
            assert.strictEqual(
                new Set(indices).size, indices.length,
                `addition at ${testCase.position} left duplicate node entries: ${JSON.stringify(indices)}`,
            );
            const before = new Map(testCase.before.nodes.map(n => [n.nodeIndex, n]));
            for (const node of testCase.after.nodes) {
                const previous = before.get(node.nodeIndex);
                if (previous && previous.publicKey !== node.publicKey) {
                    assert.ok(
                        node.generation > previous.generation,
                        `node ${node.nodeIndex} changed key without advancing its generation`,
                    );
                }
            }
        }
    });
    
    it("SECURITY: a removal refreshes every node on the departing leaf's path and no other", () => {
        for (const testCase of removals) {
            const before = new Map(testCase.before.nodes.map(n => [n.nodeIndex, n]));
            let refreshed = 0;
            for (const node of testCase.after.nodes) {
                const previous = before.get(node.nodeIndex);
                if (!previous) {
                    continue;
                }
                if (node.generation !== previous.generation) {
                    refreshed++;
                    assert.notStrictEqual(
                        node.publicKey, previous.publicKey,
                        `node ${node.nodeIndex} bumped its generation but kept its key`,
                    );
                }
            }
            // Which nodes those are is checked by validateRemoval above; here we only insist that a removal in a
            // tree with internal nodes actually refreshed something.
            if (testCase.before.nodes.length > 0) {
                assert.ok(refreshed > 0, `removal in N=${testCase.before.numLeaves} refreshed nothing`);
            }
        }
    });
});
